name: Generation du snake

on:
  # toutes les 12h
  schedule:
    - cron: "0 */12 * * *"
  # bouton manuel dans l'onglet Actions
  workflow_dispatch:
  # a chaque push sur main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Genere les images du snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: yuki640
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push sur la branche output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
